---
title: "Atividade"
author: "Wendel Dias"
date: "2024-06-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(rgbif)
library(ggplot2)
library(dplyr)
library(GGally)
library(ggthemes)
library(ggpubr)
library(tidyr)
library(ritis)
library(validate)
library(ggmap)
library(maps)
library(mapdata)


## Baixando o banco de dados de coorrência do tubarão branco direto do GBIF

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

TubBranco_gbif <- occ_data(scientificName = "Carcharodon carcharias", hasCoordinate = TRUE, hasGeospatialIssue=FALSE)

#####Dimensões
dim(TubBranco_gbif)


## Checando os problemas reportados

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 
 unique() %>% 
  strsplit(., "[,]") %>% 
  unlist()

gbif_issues() %>% 
  data.frame() %>% 
  filter(code %in% issues_gbif)

TubBranco_gbif_novo <- TubBranco_gbif$data %>%
  dplyr::select(scientificName, acceptedScientificName, decimalLatitude, decimalLongitude,
                issues, basisOfRecord, occurrenceStatus, rightsHolder, 
                datasetName, recordedBy, locality)

TubBranco_gbif_novo <- TubBranco_gbif_novo %>% 
  distinct()
knitr::opts_chunk$set(echo = TRUE)


## Checando os níveis dos fatores

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

lapply(TubBranco_gbif_novo, unique)


## Agora vou usar uma função para classificar os ocorrências suspeitas

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

flag_outlier <- function(df, species){


## funcao para classificar ocorrencias suspeitas

## baseada no calculo do centroide de todas ocorrencias

## indica como 'check' as ocorrencias que tem distancias até o centroide

## acima do 90th quantil (default) das distancias calculadas

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

  dados <- df %>% 
    dplyr::filter(scientificName == species); 
  
  dados2 <- geosphere::distVincentyEllipsoid(
    dados %>%
      summarise(centr_lon = median(decimalLongitude),
                centr_lat = median(decimalLatitude)),
    dados %>% 
      dplyr::select(decimalLongitude, decimalLatitude)
  ) %>% 
    bind_cols(dados) %>% 
    rename(dist_centroid = '...1') %>% 
    mutate(flag = ifelse(dist_centroid < quantile(dist_centroid, probs = 0.9), "OK",
                         ifelse(dist_centroid >= quantile(dist_centroid, probs = 0.90) & dist_centroid < quantile(dist_centroid, probs = 0.95), "check > Q90",
                                ifelse(dist_centroid >= quantile(dist_centroid, probs = 0.95), "check > Q95", "OK"))))
  
  # mutate(flag = ifelse(dist_centroid > quantile(dist_centroid, probs = prob), "check", "OK"))
  
  print(dados2)
  
}


## Agora vou classificar as ocorrências

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

marcados <- TubBranco_gbif$data %>% 
  data.frame() %>% 
  dplyr::select(scientificName, decimalLongitude, decimalLatitude, datasetName) %>% 
  distinct()

world <- map_data('world')


## Plotando o mapa de ocorrências do tubarão branco (Carcharodon carcharias)

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ggplot() +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  coord_fixed() +
  theme_classic() +
  geom_point(data = TubBranco_gbif_novo, aes(x = decimalLongitude, y = decimalLatitude), color = "red") +
  labs(x = "longitude", y = "latitude", title = expression(italic("Carcharodon carcharias")))


## Checando a profundidade

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

TubBranco_gbif_novo %>% 
  ggplot(aes(x = depth, fill = waterBody)) +
  geom_histogram()


## Enfim, chegamos na parte do OBIS

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages("robis")
library(robis)

Tubarao_obis <- robis::occurrence("Carcharodon carcharias")


## Checando os dados

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

names(Tubarao_obis)

Tubarao_obis_novo <- Tubarao_obis %>% 
  dplyr::select(scientificName, decimalLatitude, decimalLongitude, bathymetry,
                flags, waterBody, basisOfRecord, occurrenceStatus, rightsHolder, 
                datasetName, recordedBy, depth, locality, habitat) %>% 
  distinct()


## Checando agora os problemas reportados (famosos flags)

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Tubarao_obis_novo %>% 
  distinct(flags)


## Checando se há Nas no datasetName

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Tubarao_obis_novo %>% 
  filter(!flags %in% c("no_depth,on_land", "on_land", "on_land,depth_exceeds_bath", "depth_exceeds_bath,on_land"),
         is.na(datasetName)) %>% 
  distinct(waterBody)


## Depth está OK

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Tubarao_obis_novo %>% 
  filter(!flags %in% c("no_depth,on_land", "on_land", "on_land,depth_exceeds_bath", "depth_exceeds_bath,on_land"),
         !is.na(datasetName),
         !waterBody %in% c("Mar Caribe", "atlantique", "South Atlantic", "Atlantic Ocean", "Caribe", "Bahia de La Habana", "WESTERN ATLANTIC", "Gulf of Mexico", "CARIB")) %>% 
  ggplot(aes(x = depth, fill = waterBody)) +
  geom_histogram() 


## Checando os níveis

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Tubarao_obis_novo %>% 
  filter(!flags %in% c("no_depth,on_land", "on_land", "on_land,depth_exceeds_bath", "depth_exceeds_bath,on_land"),
         !is.na(datasetName),
         !waterBody %in% c("Mar Caribe", "atlantique", "South Atlantic", "Atlantic Ocean", "Caribe", "Bahia de La Habana", "WESTERN ATLANTIC", "Gulf of Mexico", "CARIB")) %>% 
  lapply(., unique)


## Agora está tudo OK

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Tubarao_obis_mod <- Tubarao_obis_novo %>% 
  filter(!flags %in% c("no_depth,on_land", "on_land", "on_land,depth_exceeds_bath", "depth_exceeds_bath,on_land"),
         !is.na(datasetName),
         !waterBody %in% c("Mar Caribe", "atlantique", "South Atlantic", "Atlantic Ocean", "Caribe", "Bahia de La Habana", "WESTERN ATLANTIC", "Gulf of Mexico", "CARIB", NA))


## Agora plotando o mapa OK

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ggplot() +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  coord_fixed() +
  theme_classic() +
  geom_point(data = Tubarao_obis_mod, aes(x = decimalLongitude, y = decimalLatitude, color = waterBody)) +
  labs(x = "longitude", y = "latitude", title = expression(italic("Carcharodon carcharias")))


## Unindo o GBIF e o OBIS
# Ver as diferenças

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setdiff(names(Tubarao_obis_novo), names(Tubarao_obis_mod))

setdiff(names(Tubarao_obis_novo), names(Tubarao_obis_mod))


## Carregando e instalando pacotes necessários para rodar as análises

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
install.packages("tribble")
library(tibble)


## Todos os dados

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

all_data <- bind_rows(Tubarao_obis_novo %>% 
                        mutate(repo = paste0("gbif", row.names(.))), 
                      Tubarao_obis_mod %>% 
                        mutate(repo = paste0("obis", row.names(.)))) %>%
  column_to_rownames("repo") %>% 
  dplyr::select(decimalLongitude, decimalLatitude, depth) %>% 
  distinct() %>% 
  rownames_to_column("occ") %>% 
  separate(col = "occ", into = c("datasetName", "rn"), sep = 4) %>%
  mutate(scientificName = "Carcharodon carcharias") %>% 
  dplyr::select(-rn)


## Mapeando as ocorrências

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

ggplot() +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  coord_fixed() +
  theme_classic() +
  geom_point(data = all_data, aes(x = decimalLongitude, y = decimalLatitude, color = datasetName)) +
  #theme(legend.title = element_blank()) +
  labs(x = "longitude", y = "latitude", title = expression(italic("Carcharodon carcharias")))

dir.create("data")
write.csv(all_data, "data/occ_GBIF-OBIS_tub_branco.csv", row.names = FALSE)
